name: SSH to VM and List Containers

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  ssh-and-list-containers:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and list containers
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.SSH_HOST  }}
            USER_NAME : ${{ secrets.SSH_USER  }}
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -i private_key -o 'StrictHostKeyChecking=no' ${USER_NAME}@${HOSTNAME} "
            echo "Hello from the test VM "
