name: SSH to VM and List Containers

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  ssh-and-list-containers:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and list containers
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker ps -a"
